// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkxZFt2OQxUu9bMXjSF0YIIcAtaV1ZTvQ',
    appId: '1:749395725893:web:61aa0dd961cf183b139d2c',
    messagingSenderId: '749395725893',
    projectId: 'attendance-49ec6',
    authDomain: 'attendance-49ec6.firebaseapp.com',
    storageBucket: 'attendance-49ec6.firebasestorage.app',
    measurementId: 'G-ZFESW8B3XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDApoy-vXOfskcRRoV_uEqrT2MTHSPy0rY',
    appId: '1:749395725893:android:07936c281b1147b4139d2c',
    messagingSenderId: '749395725893',
    projectId: 'attendance-49ec6',
    storageBucket: 'attendance-49ec6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3MSfRfkPcCvznlm1p_JECoPlpfBfrbcQ',
    appId: '1:749395725893:ios:0448d2d3269e6ed4139d2c',
    messagingSenderId: '749395725893',
    projectId: 'attendance-49ec6',
    storageBucket: 'attendance-49ec6.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3MSfRfkPcCvznlm1p_JECoPlpfBfrbcQ',
    appId: '1:749395725893:ios:0448d2d3269e6ed4139d2c',
    messagingSenderId: '749395725893',
    projectId: 'attendance-49ec6',
    storageBucket: 'attendance-49ec6.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkxZFt2OQxUu9bMXjSF0YIIcAtaV1ZTvQ',
    appId: '1:749395725893:web:15174f3bb2f66706139d2c',
    messagingSenderId: '749395725893',
    projectId: 'attendance-49ec6',
    authDomain: 'attendance-49ec6.firebaseapp.com',
    storageBucket: 'attendance-49ec6.firebasestorage.app',
    measurementId: 'G-C95V9111H3',
  );
}
